# 
#   Copyright (c) 2017 Philipp Paulweber
#   All rights reserved.
# 
#   Developed by: Philipp Paulweber
#                 https://github.com/ppaulweber/docker-cpp
# 
#   This file is part of docker-cpp.
# 
#   docker-cpp is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
# 
#   docker-cpp is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#   GNU General Public License for more details.
# 
#   You should have received a copy of the GNU General Public License
#   along with docker-cpp. If not, see <http://www.gnu.org/licenses/>.
# 

* docker-cpp: C++ Build Environment Docker Container Image

TBD


** Copyright and License

The copyright holder of 
docker-cpp is the Philipp Paulweber ([[https://github.com/ppaulweber][@ppaulweber]]) 
and the used license of 
docker-cpp is a [[https://www.gnu.org/licenses/gpl-3.0.html][GNU GPLv3+]].

*** Notice

#+begin_src

Copyright (c) 2017 Philipp Paulweber
All rights reserved.

Developed by: Philipp Paulweber
              https://github.com/ppaulweber/docker-cpp

This file is part of docker-cpp.

docker-cpp is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

docker-cpp is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with docker-cpp. If not, see <http://www.gnu.org/licenses/>.

#+end_src
