# 
#   Copyright (C) 2017-2018 Philipp Paulweber
#   All rights reserved.
# 
#   Developed by: Philipp Paulweber
#                 <https://github.com/ppaulweber/docker-cpp>
# 
#   This file is part of docker-cpp.
# 
#   docker-cpp is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
# 
#   docker-cpp is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#   GNU General Public License for more details.
# 
#   You should have received a copy of the GNU General Public License
#   along with docker-cpp. If not, see <http://www.gnu.org/licenses/>.
# 

* docker-cpp: C++ Build Environment Docker Container Image

Provides a =Dockerfile= which creates a C++ build environment with 
different GNU =gcc= and LLVM =clang= C++ compiler versions and several other tools.
There exists an automated build process hosted and located at https://hub.docker.com/ppaulweber/docker-cpp.
The =master= branch equals the =:latest= docker image tag.
Furthermore, there exists a tool =base= branch (and docker image tag) 
which covers some generic tools like =cmake=.
For every GNU =gcc= and LLVM =clang= version exists an explicit branch (and docker image tag).
The latest version of all sub-branches are merged together into the =master= branch. 


** Copyright and License

The copyright holder of 
docker-cpp is the Philipp Paulweber ([[https://github.com/ppaulweber][@ppaulweber]]) 
and the used license of 
docker-cpp is a [[https://www.gnu.org/licenses/gpl-3.0.html][GNU GPLv3+]].

*** Notice

#+begin_src

Copyright (C) 2017-2018 Philipp Paulweber
All rights reserved.

Developed by: Philipp Paulweber
              <https://github.com/ppaulweber/docker-cpp>

This file is part of docker-cpp.

docker-cpp is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

docker-cpp is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with docker-cpp. If not, see <http://www.gnu.org/licenses/>.

#+end_src
